version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
      - ./templates:/app/templates
      - ./static:/app/static
      - ./alembic:/app/alembic
      - ./alembic.ini:/app/alembic.ini
      - ./logs:/app/logs
      - ./uploads:/app/uploads
    environment:
      - REDIS_URL=redis://redis:6379
      - ENVIRONMENT=production
    depends_on:
      redis:
        condition: service_healthy
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    restart: unless-stopped

  celery_worker:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
    environment:
      - REDIS_URL=redis://redis:6379
      - ENVIRONMENT=production
    depends_on:
      redis:
        condition: service_healthy
    command: celery -A src.celery_app worker --loglevel=info --concurrency=2
    restart: unless-stopped
